### ISSUE TITLE
[Query] How to get those illustrations from dribble design?

### ISSUE THREAD

**Issue by sattasundar** [RadekVyM/FourSeasons#1]
Hey @RadekVyM ,  Hope you are doing well. I am also a mobile app developer.
So any idea, how to get those illustrations from any dribble design?

Thanks 🙂

**Comment by RadekVyM** [comment]
> Hey @RadekVyM , Hope you are doing well. I am also a mobile app developer. So any idea, how to get those illustrations from any dribble design?
> 
> Thanks 🙂

Hi @sattasundar,
do you mean something like these illustrations?

![autumn](https://user-images.githubusercontent.com/65116078/185945031-3d265dfb-cad8-499a-8fd3-0ad40787999d.jpg)
![rainy](https://user-images.githubusercontent.com/65116078/185945097-73086cef-4842-48ea-b483-2a174b43ed41.jpg)
![summer](https://user-images.githubusercontent.com/65116078/185945124-56a8a4fe-01bf-4ffb-8a46-5830368d4a10.jpg)

I usually choose designs with attached illustrations or with illustrations and images that are easily findable on the Internet (using e.g. **Google Photos** or **Google Lens**). For example illustrations shown above are luckily attached to the original design by its author. Sometimes if I do not need a high quality image, I just cut out the image from a sample image - e.g. these I just cut out:

![festival](https://user-images.githubusercontent.com/65116078/185948669-11980cbe-12fc-4b92-98f4-8f2c18512851.png)
![hiking](https://user-images.githubusercontent.com/65116078/185948701-21b0e15d-276d-4a60-b524-d07304dbea21.png)

I hope I have answered your question.

**Comment by sattasundar** [comment]
Got it. Thanks @RadekVyM
